### ISSUE TITLE
Email Address

### ISSUE THREAD

**Issue by stephenlane** [adlnet/SCORM-to-xAPI-Wrapper#2]
Hi There,

Does the email address from the LMS get sent to the LRS

Regards,

Stephen

**Comment by jonopoltrack** [comment]
Stephen -

The wrapper is coded to use an "account" as the actor.

When using an account you have to provide a "homePage" and "name", where the homePage is the system providing the user information.  This is what the example JSON may look like:

 "actor": {
    "account": {
      "homePage": "http://myLMS.com",
      "name": "user123"
    },
    "objectType": "Agent"
  }

In our Roses Example, we just use the LMS home page, but this could also be some a bit more involved, like an endpoint for a user management service.

As far as "name", this is to be an identifier for the user in the system (homePage).  When a SCO initializes, we get the cmi.learner_name (or for SCORM 1.2 cmi.core.student_id) from the LMS and use that as the "name" in the statement.  Some LMSs use an email to identify the student, so that is what you get back.  Other times, you may just get an identifier or some other value used to uniquely refer to a user.  The user identifier in SCORM must be a URI per RFC 3986, but beyond that, there is no guidance on exactly how to form these URIs.

Take a look at our example use of the wrapper here - https://github.com/adlnet/SCORM-to-TLA-Roadmap/tree/master/examples/RosesCourseConversion

I hope this helps

**Comment by stephenlane** [comment]
Hi @jonopoltrack,

Thanks for the reply. What you have said makes perfect sense. The reason why I am inquiring about the email address is solely for analytics purposes. I am currently using learning locker as my lrs and moodle as my LMS. I will be migrating to blackboard shortly. 

If I use a bookmarklet to send content to my lrs the following is the xapi statement received:

{
    "version": "1.0.0",
    "id": "c9200f3f-c5d6-4772-ac44-28b3afb2407b",
    "timestamp": "2015-03-24T15:15:45.652Z",
    "actor": {
        "objectType": "Agent",
        "mbox": "mailto:student1@test.com",
        "name": "Larry"
    },

However if I use the wrapper and send stuff to my lrs I am missing the mbox which for analytics purposes is important as it means there is more to work with. 

So the question/issue I'm really having is, is it  possible to get an email address using this wrapper and send it to an LRS.

Thanks in advance.

Stephen

**Comment by jonopoltrack** [comment]
Hey Stephen -

You can make these changes, but it will require some updates to the code.

You'll have to update https://github.com/adlnet/SCORM-to-xAPI-Wrapper/blob/master/SCORMToXAPIFunctions.js

This probably isn't a complete list, but it will give you an idea of what needs to change 

lines 74-81 in getBaseStatement will need to be updated so the template uses mbox instead of an account.

You'll need to do the same in getInteractionsBaseStatement and getVoidedBaseStatement.

You'll need to update getAgent (on line 229) to return the mbox instead of account also.

I would search for "account:" in the code.  You'll pretty much have to update the JSON at each place you see account used.

Finally, in several places, you will see

```
  if (window.localStorage.learnerId == null)
  {
     window.localStorage.learnerId = retrieveDataValue(scormVersionConfig.learnerIdElement);
  }
```

This code adds the learner id to local storage.  this is what is used as the account-name.  If the LMS you are using uses the username as the SCORM cmi.learner_id, then you won't need to change anything.  If you are getting the email address used in mbox elsewhere, change these lines.

I will add a separate issue to abstract the use of the account to a single place in this code.  Then your use case will be easier to support.

**Comment by stephenlane** [comment]
Hey @jonopoltrack 

Thanks for the pointers. Just so that I am clear and don't end up going don a rabbit hole. It is possible to get the email address through javascript with changes to the wrapper.

Thanks for you extremely helpful help.

Thanks,

Stephen

**Comment by jonopoltrack** [comment]
Stephen -

It depends on the LMS you're using.  So the wrapper, as it is currently implemented, depends on the LMS to return the user ID with a call to 

in SCORM 2004 - GetValue("cmi.learner_id");
in SCORM 1.2 - LMSGetValue("cmi.core.student_id");

The LMS largely controls what comes back from those calls.  _I have seen LMSs return the user's email address_ in response to these calls, but that is an implementation decision, not specified by SCORM.  There is no standardized way using the SCORM API/Data Model to get the user's email from the LMS.

Keep in mind that the LMS you are using may provide another way, outside of SCORM, to do this.  This is also highly dependent on your specific LMS.  If you know what LMS you're going to be running your content in, I'd suggest trying it the way the wrapper currently works, and see if you get an email address back as the "name" in the account object.  If you do, then all you'll need to do is restructure the json so its an mbox instead.  If you do not get back an email address, then you'll probably need to contact your LMS vendor, or if its open source, read the documentation to see if you can get the email address via a service or something..  

I hope this helps.

**Comment by stephenlane** [comment]
Hey @jonopoltrack 

As I feared there is no official way. Heres hoping blackboard have been kind in there implementation.

Thanks for the info.

Stephen
