### ISSUE TITLE
How can I use it in some course without APIwrapper.js?

### ISSUE THREAD

**Issue by StarsHu** [adlnet/SCORM-to-xAPI-Wrapper#8]
Some course is just a link, for example a video player, do not have APIwrapper.js in package.

**Comment by jono-poltrack** [comment]
Hi StarsHu.  If you look at the APIWrapper.js file in the SCORM 2004 directory, this has been updated so that it only takes 3 simple changes to integrate/convert.  You can put this in your own courses in initialize, terminate and setvalue.  Look for "xapi" in the comments in that file and you'll see the integration points.

Also check out https://github.com/adlnet/Starting-from-SCORM-A-Developers-Guide 

I hope this helps
